# https://docs.pytest.org/en/stable/customize.html#pyproject-toml

# https://mypy.readthedocs.io/en/stable/config_file.html#using-a-pyproject-toml-file
# https://github.com/python/mypy/issues/5205
[tool.mypy]
python_version = "3.11"
platform = "linux"
pretty = true
show_error_codes = true
show_column_numbers = true
ignore_missing_imports = true

### Disallow dynamic typing
#disallow_any_expr = true
disallow_any_generics = true

### Untyped definitions and calls
disallow_untyped_calls = false
disallow_untyped_defs = true

### None and Optional handling
no_implicit_optional = false
strict_optional = true

### Configuring warnings
warn_redundant_casts = true
warn_no_return = true
warn_return_any = true
warn_unreachable = true

[[tool.mypy.overrides]]
module = "tests.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "pinwheel.callbacks.*"
ignore_errors = true

# https://github.com/google/yapf/issues/708
[tool.yapf]
based_on_style = "facebook"
column_limit = 120
coalesce_brackets = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra --color=yes"
filterwarnings = """
  ignore::DeprecationWarning
"""
testpaths = ["tests"]

[tool.isort]
profile = "django"
line_length = 120
force_grid_wrap = 3
combine_star = true
combine_as_imports = true
remove_redundant_aliases = true
color_output = true
skip_glob = [
  "hack/**"
]

[tool.black]
skip-string-normalization = true
max-line-length = 120
line-length = 120
